import type { Category, MenuItem } from '@/types';

export const categories: Category[] = [
  { id: 'breakfast', name: 'Breakfast' },
  { id: 'main-courses', name: 'Main Courses' },
  { id: 'desserts', name: 'Desserts' },
  { id: 'drinks', name: 'Drinks' },
];

export const menuItems: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Classic Avocado Toast',
    description: 'Thick-cut sourdough topped with fresh avocado, chili flakes, and a squeeze of lime.',
    price: 12.50,
    imageId: 'avocado-toast',
    category: 'breakfast',
    tags: ['veg', 'new'],
    ingredients: ['Sourdough Bread', 'Avocado', 'Chili Flakes', 'Lime', 'Salt', 'Pepper'],
  },
  {
    id: 'item-2',
    name: 'Artisan Latte',
    description: 'Perfectly balanced espresso with steamed milk, topped with beautiful latte art.',
    price: 5.00,
    imageId: 'coffee-art',
    category: 'drinks',
    tags: ['veg'],
    ingredients: ['Espresso', 'Milk'],
  },
  {
    id: 'item-3',
    name: 'Almond Croissant',
    description: 'A flaky, buttery croissant filled with sweet almond paste and topped with toasted almonds.',
    price: 6.50,
    imageId: 'croissant',
    category: 'breakfast',
    tags: ['veg'],
    ingredients: ['Flour', 'Butter', 'Sugar', 'Almonds', 'Yeast'],
  },
  {
    id: 'item-4',
    name: 'Berry Cheesecake',
    description: 'Creamy New York style cheesecake with a graham cracker crust and a tart berry compote.',
    price: 8.00,
    imageId: 'cheesecake',
    category: 'desserts',
    tags: ['veg'],
    ingredients: ['Cream Cheese', 'Sugar', 'Eggs', 'Berries', 'Graham Cracker'],
  },
  {
    id: 'item-5',
    name: 'Quinoa Power Salad',
    description: 'A vibrant mix of quinoa, roasted vegetables, chickpeas, and a zesty lemon-tahini dressing.',
    price: 15.00,
    imageId: 'salad-bowl',
    category: 'main-courses',
    tags: ['veg', 'gluten-free'],
    ingredients: ['Quinoa', 'Bell Peppers', 'Zucchini', 'Chickpeas', 'Lemon', 'Tahini'],
  },
  {
    id: 'item-6',
    name: 'Spicy Chicken Sandwich',
    description: 'Crispy fried chicken breast with a spicy slaw and pickles on a toasted brioche bun.',
    price: 16.50,
    imageId: 'sandwich',
    category: 'main-courses',
    tags: ['spicy'],
    ingredients: ['Chicken Breast', 'Brioche Bun', 'Cabbage', 'Mayonnaise', 'Spices', 'Pickles'],
  },
  {
    id: 'item-7',
    name: 'Classic Iced Tea',
    description: 'Freshly brewed black tea, lightly sweetened and served over ice with a lemon wedge.',
    price: 4.00,
    imageId: 'iced-tea',
    category: 'drinks',
    tags: ['veg', 'gluten-free'],
    ingredients: ['Black Tea', 'Water', 'Sugar', 'Lemon'],
  },
];
